### ISSUE TITLE
Correctness of `dom` in 0.2.1

### ISSUE THREAD

**Issue by knothed** [AndreasPK/dom-lt#2]
The following rooted graph will produce an incorrect `dom` result with version `0.2.1`:

```
g = (0, fromAdj [(0,[3,6]), (3,[8,9]), (6,[99]), (8,[11]), (9,[16]), (11,[99]), (12,[99]), (13,[99]), (16,[12,13]), (99,[])])
```

Consider the node `99`.
There are multiple ways from `0` to `99`, for example:
```
0 -> 3 -> 8 -> 11 -> 99
0 -> 3 -> 9 -> 16 -> 12 -> 99
0 -> 6 -> 99
```

This means that neither `3` nor `6` can be a dominator of `99`.

But now, the result of `dom g` (using version `0.2.1`) is:
```
dom g = [(3,[0]),(6,[0]),(8,[3,0]),(9,[3,0]),(11,[8,3,0]),(16,[9,3,0]),(12,[16,9,3,0]),(13,[16,9,3,0]),(99,[6,0])]
```
Looking at node `99`, it names `6` as a dominator, which is wrong – the only correct dominator of `99` is `0`.

---

Using version `0.2.0` we would get the correct result:
```
dom g = [(3,[0]),(6,[0]),(99,[0]),(8,[3,0]),(9,[3,0]),(11,[8,3,0]),(16,[9,3,0]),(12,[16,9,3,0]),(13,[16,9,3,0])]
```

Interestingly, this issue was **not** just introduced in 0.2.1 – it also existed in 0.1.3.
We get the exact same (incorrect) result for `dom g` with version 0.1.3 as we get with 0.2.1.

**Comment by AndreasPK** [comment]
> Interestingly, this issue was **not** just introduced in 0.2.1 – it also existed in 0.1.3.
> We get the exact same (incorrect) result for `dom g` with version 0.1.3 as we get with 0.2.1.

Interesting and unfortunate. I did not intend to make semantic changes between 0.1.3 and 0.2.1 (I primarily picked up maintenance to ensure the package keeps compiling). Mostly because I was not aware of any broken logic.

Although this great report should make it easier it will likely take me a bit until I can look at this in depth. If you or anyone else want's to look at this let me know. Otherwise I will try to take the time to look at this next week.

**Comment by knothed** [comment]
I sadly do not have the time to look into this right now.
But I would be amazed if you'd tackle this next week or so - no hurry!

**Comment by knothed** [comment]
Hi, do you have any new progress on this?

**Comment by AndreasPK** [comment]
> Hi, do you have any new progress on this?

I haven't forgotten, but it's just a entry on my todo list still :(

**Comment by AndreasPK** [comment]
For clarity here is the graph showcasing the issue rendered:

![grafik](https://user-images.githubusercontent.com/5500646/90646175-31837980-e237-11ea-9744-a080f5d84820.png)

I was able to confirm the issue locally at least.

**Comment by sgraf812** [comment]
This one is even simpler:

![graph(1)](https://user-images.githubusercontent.com/1151264/91018874-72d9a780-e5f0-11ea-9e51-b3cd2c5f419c.png)

The total order on node numbers seems very relevant. For example, swapping 3 and 4 leads to a correct result.
I also think that for this graph, we should have sdom = idom. A bit of printf debugging revealed that sdom as stored in `bucketE` is already broken.

**Comment by sgraf812** [comment]
Here's a fix:

```diff
diff --git a/Data/Graph/Dom.hs b/Data/Graph/Dom.hs
index 11688f4..c1c449a 100644
--- a/Data/Graph/Dom.hs
+++ b/Data/Graph/Dom.hs
@@ -154,6 +154,7 @@ idomM = do
     sw <- sdnoM w
     ps <- predsM w
     forM_ ps (\v-> do
+      sw <- sdnoM w
       u <- eval v
       su <- sdnoM u
       when (su < sw)
```

That loop has to compare to the current minimum, not the value it started with (which is the DFS number of the node in question).

**Comment by knothed** [comment]
This seems to work. Thank you!
